force-app/main/default/objects/NamespaceSetting__c/NamespaceSetting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>NamespaceSetting</label>
</CustomObject>

force-app/main/default/objects/NamespaceSetting__c/fields/Prefix__c.field-meta.xml
<CustomField>
    <fullName>Prefix__c</fullName>
    <label>Prefix</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrgSignatureKey__c/OrgSignatureKey__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>OrgSignatureKey</label>
</CustomObject>

force-app/main/default/classes/PostInstallClass.cls
global class PostInstallClass implements InstallHandler {
	global void onInstall(InstallContext context) {
		NamespaceSetting__c setting = NamespaceSetting__c.getOrgDefaults();
		if (String.isBlank(setting.Prefix__c)) { 
			setting.Prefix__c = PostInstallClass.class.getName().substringBefore('PostInstallClass').substringBefore('.');
			setting.Prefix__c += !String.isBlank(setting.Prefix__c) ? '__' : '';
			upsert setting;
		}
		
		OrgSignatureKey__c orgSignatureKey = OrgSignatureKey__c.getOrgDefaults();
		if (String.isBlank(orgSignatureKey.key__c)) { registerOrg(); }
	}

	@future(callout=true)
	public static void registerOrg(){
		Map<String,Object> res = DocHubRegisterController.registerOrg();
	}
}