force-app/main/default/objects/Doc_Hub_Link__c/Doc_Hub_Link__c.object-meta.xml
<CustomObject>
    <label>Doc Hub Link</label>
    <nameField>
        <displayFormat>DHL-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Doc Hub Links</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Doc_Hub_Link__c/fields/Auto_Publish__c.field-meta.xml
<CustomField>
    <fullName>Auto_Publish__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Auto Publish</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Doc_Hub_Link__c/fields/Connection_Id__c.field-meta.xml
<CustomField>
    <fullName>Connection_Id__c</fullName>
    <label>Connection Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Doc_Hub_Link__c/fields/Origin_Id__c.field-meta.xml
<CustomField>
    <fullName>Origin_Id__c</fullName>
    <label>Origin Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Doc_Hub_Log__c/Doc_Hub_Log__c.object-meta.xml
<CustomObject>
    <label>Doc Hub Log</label>
    <nameField>
        <displayFormat>Log-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Doc Hub Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Doc_Hub_Log__c/fields/Response_Code__c.field-meta.xml
<CustomField>
    <fullName>Response_Code__c</fullName>
    <label>Response Code</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/OrgSignatureKey__c/OrgSignatureKey__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>OrgSignatureKey</label>
</CustomObject>

force-app/main/default/classes/DocumentViewPageControllerTest.cls
// @isTest(SeeAllData=true)
@isTest
public class DocumentViewPageControllerTest {
	@TestSetup
	static void makeData(){
		insert new OrgSignatureKey__c(key__c = '345678');
	}
	@isTest static void loadDocumentTest(){
		DocumentViewPageController doc = new DocumentViewPageController();
		
		DocHubMockForConnectionController mock = new DocHubMockForConnectionController();
		Test.setMock(HTTPCalloutMock.class, mock);

		
		doc.loadDocument();
		System.assertEquals('Sorry, something went wrong', doc.errorMessage);

		Doc_Hub_Link__c dhl = new Doc_Hub_Link__c(
			Connection_Id__c = NULL,
			Origin_Id__c = '1xRc2xVCMG72uH8EIskmftTNHlvb5ck4JI77CYFMwHhE',
			Auto_Publish__c = true
		);
		insert dhl;

		ApexPages.currentPage().getParameters().put('Id', dhl.Id);
		doc.loadDocument();
		System.assertEquals('Sorry, something went wrong', doc.errorMessage);

		dhl.Connection_Id__c = '9';
		update dhl;
		Date toDay = Date.toDay();
		Test.startTest();
			doc.loadDocument();
			List<Doc_Hub_Log__c> listLog = [SELECT Date__c, Method__c, Request__c, Response__c, Response_Code__c
											FROM Doc_Hub_Log__c LIMIT 1];
			Map<String, Object> resMap = (Map<String, Object>) JSON.deserializeUntyped(listLog[0].Response__c);
			System.assertEquals('Success', resMap.get('status'));
			System.assertEquals(toDay, listLog[0].Date__c);
			System.assertEquals('documentfetch', listLog[0].Method__c);
			System.assertEquals('d9cc6b5a-9b04-4981-aa11-e9fecee56afb', resMap.get('result'));
		Test.stopTest();
	
	}

	@isTest static void loadDocumentTestFail(){
		DocumentViewPageController doc = new DocumentViewPageController();
		
		DocHubMockForConnectionController mock = new DocHubMockForConnectionController();
		Test.setMock(HTTPCalloutMock.class, mock);
		Doc_Hub_Link__c dhl = new Doc_Hub_Link__c(
			Connection_Id__c = 'testConnectionId',
			Origin_Id__c = 'testOriginIdc',
			Auto_Publish__c = true
		);
		insert dhl;
		ApexPages.currentPage().getParameters().put('Id', dhl.Id);
		
		Date toDay = Date.toDay();
		Test.startTest();
			doc.loadDocument();
			List<Doc_Hub_Log__c> log = [SELECT Date__c, Method__c, Response__c, Response_Code__c FROM Doc_Hub_Log__c];
			Map<String, Object> res = (Map<String, Object>) JSON.deserializeUntyped(log[0].Response__c);
			System.assertEquals(toDay, log[0].Date__c);
			System.assertEquals('Error', res.get('status'));
			System.assertEquals('{message=invalid input syntax for integer: testConnectionId}', String.valueOf(res.get('error')));
		Test.stopTest();
	}
}